### ISSUE TITLE
cross mode compatibility

### ISSUE THREAD

**Issue by fjenett** [studioijeoma/ijeomamotion#1]
Hey,

i see what the problem is .. but there's a sane JS way (besides it using eval) around it without having to introduce differing syntax from the Java mode.

Your problem is that you can't access the "private" variables of the object that is passed into the library classes. There is one way around this, let the objects themselfs access and set them for you:

Assume in the outside scope you only have the name of the property (private var) and the object (closure).

```
var sketchObject = Processing.getInstanceById("mySketchName");
var propertyName = "x1";
```

Now prepare a generic accessor function to set a property by given name to a value.

```
var getUpdateFunc = function ( prop ) { return eval( "( function (v) { "+prop+" = v } )" ) };
var updateSketchX1 = getUpdateFunc( "x1" );
```

Whatever object you are now calling updateSketchX1 function on will try to set a "x1" to a given value. So, to update that value inside the sketch it's just:

```
var aValue = 300;
updateSketchX1.apply( sketchObject, [aValue] );
```

The same could be done to read the values by just creating a function that returs the value from the scope the function is called upon.

Note that "sketchObject" here holds the same object as "this" refers to inside a sketch's code: a Processing.Processing instance.

**Comment by studioijeoma** [comment]
Thanks for posting! I tried using eval in the same way to access a var inside the processing closure from outside but its returning undefined...
http://jsfiddle.net/8z4h3/1/

**Comment by fjenett** [comment]
Hm, ... i tested and it worked for me before but i'm not seeing what i did different. I'm gonna look into it next week as i'm too busy right now.

**Comment by fjenett** [comment]
You are right it does not seem to be possible. ... not sure how i tricked myself into believing it would.

**Comment by studioijeoma** [comment]
Thanks for trying anyhow! I cc'd processing.org and co on those tweets with that example and they never replied... it'd be great to know why they're putting everything in a closure... I checked out the src for motion.lib, the only other animation lib for processing.js, and they had the same problem. Their lib can only animate vars that are within objects.

**Comment by fjenett** [comment]
The easiest and most direct way to get in touch with PJS team is the IRC channel. They are there 24/7 ... :)

irc://irc.mozilla.org/processing.js
